### ISSUE TITLE
run staticcheck

### ISSUE THREAD

**Issue by marten-seemann** [ipld/.github#6]
See https://github.com/ipld/ipld/pull/92.

**Comment by marten-seemann** [comment]
Interestingly, it looks like `staticcheck` integration in golangci-lint is broken: https://github.com/golangci/golangci-lint/issues/1649.

**Comment by marten-seemann** [comment]
We should use the real staticcheck, not the one bundled with golangci-lint.

Unfortunately, that one doesn't give us proper annotations: https://github.com/dominikh/go-tools/issues/910.
The was submitted a long time ago in https://github.com/actions/setup-go/pull/98, but it looks like nobody in the GitHub team seems to care.

@mvdan Any suggestions how to move forward with this?

**Comment by mvdan** [comment]
I have a friend who is an engineer on the Actions team, I've pinged him about this whole situation in the hopes that he can reach the right person. Let's wait a week and hopefully it gets resolved by then.

If we're still here in a week, maybe we can run staticcheck's output via a simple sed script to make its output match what setup-go expects. This is roughly what we'd gain with golangci-lint, and it brings its own downsides, so I think a sed line should be better. I don't think we want to encourage others to use a third-party setup-go action just yet.

**Comment by marten-seemann** [comment]
FWIW, I tried out setup-go-faster in my demo repo, and it seems to work: https://github.com/marten-seemann-test/target/blob/master/.github/workflows/go-check.yml
