### ISSUE TITLE
What's the correct way to install dependencies?

### ISSUE THREAD

**Issue by marten-seemann** [ipld/.github#7]
Currently we use `go install` to install dependencies:
https://github.com/ipld/.github/blob/738ae9ec7a27b6dddb266cccb6edfb17b418eb74/workflow-templates/go-test.yml#L21-L22

This seems to work fine, as long as the test files don't use any additional dependencies. Otherwise, those additional dependencies are installed only when running `go test`, see https://github.com/libp2p/go-libp2p-quic-transport/runs/1739483487 for an example.

Now there 2 things we can do here:
* Use `go mod download -x` instead of `go install` to download *all* dependencies.
* Remove this step, and just have `go test` deal with pulling dependencies.

cc @mvdan

**Comment by mvdan** [comment]
I don't understand what you mean by "install dependencies". Like you say, commands like `go test` will already download whatever modules are needed and not yet in the cache.

So yeah, I would just remove this step. You could do a `go mod download`, but it's unnecessary, and it might also actually slow down CI. A `go test ./...` can be more clever and start testing some packages while others are still downloading dependencies, for example. Or maybe it doesn't actually need to download all indirectly required modules.

**Comment by marten-seemann** [comment]
> I don't understand what you mean by "install dependencies". Like you say, commands like go test will already download whatever modules are needed and not yet in the cache.

The idea was to make the execution time of each step meaningful, but that would require `go test` to not download any dependencies. Maybe this shouldn't have been a goal to begin with though.

**Comment by mvdan** [comment]
If you don't want the downloading to generally be part of the runtime of the tests, you could always use caching :)

**Comment by marten-seemann** [comment]
The `go install` step was removed in #8.
